import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles(theme => ({
  bubble: {
    position: 'relative',
    padding: theme.spacing(1),
    borderWidth: 1,
    borderRadius: 4,
    borderTopLeftRadius: 0,
    borderStyle: 'solid',
    backgroundColor: theme.palette.primary.lightest,
    borderColor: theme.palette.primary.lighter,
    '&::before': {
      content: "''",
      display: 'block',
      position: 'absolute',
      top: -1,
      left: -12,
      width: 0,
      height: 0,
      borderStyle: 'solid',
      borderWidth: '0 11px 11px 0',
      borderColor: 'transparent',
      borderRightColor: theme.palette.primary.lighter,
    },
    '&::after': {
      content: "''",
      display: 'block',
      position: 'absolute',
      top: 0,
      left: -10,
      width: 0,
      height: 0,
      borderStyle: 'solid',
      borderWidth: '0 10px 10px 0',
      borderColor: 'transparent',
      borderRightColor: theme.palette.primary.lightest,
    },
  },
  ownBubble: {
    backgroundColor: theme.palette.secondary.lightest,
    borderColor: theme.palette.secondary.lighter,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 0,
    '&::before': {
      left: 'auto',
      right: -12,
      borderWidth: '11px 11px 0 0',
      borderRightColor: 'transparent',
      borderTopColor: theme.palette.secondary.lighter,
    },
    '&::after': {
      left: 'auto',
      right: -10,
      borderWidth: '10px 10px 0 0',
      borderRightColor: 'transparent',
      borderTopColor: theme.palette.secondary.lightest,
    },
  },
}));
